version: "3.9"

services:
  # ---------------- BACKEND ----------------
  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - qdrant
    environment:
      DATABASE_URL: postgresql://ragraph:ragraph_dev@postgres:5432/ragraph
      REDIS_URL: redis://redis:6379
      QDRANT_URL: http://qdrant:6333
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  # ---------------- FRONTEND ----------------
  frontend:
    build: ../frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8000
    command: npm run build && npm start

  # ---------------- POSTGRES ----------------
  postgres:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ragraph
      POSTGRES_USER: ragraph
      POSTGRES_PASSWORD: ragraph_dev

  # ---------------- QDRANT ----------------
  qdrant:
    image: qdrant/qdrant:v1.12.1
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  # ---------------- REDIS ----------------
  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pgdata:
  qdrant_data:
  redis_data: